function figh = dualplot( ...
    x_upper, y_upper, ...
    x_lower, y_lower, ...
    lo_limit_index, hi_limit_index, estimate, ...
    x_label, y_label_upper, y_label_lower ...
    )

% figure
figh = figure;
figh.Color = 'white';
fig_size = 450;
figh.Position = [ 100 100 fig_size fig_size ];

% subplot positions
border_thickness = 0.125;
bottom_edge_location = border_thickness;
left_edge_location = border_thickness;
total_plot_height = 1 - ( 2 * border_thickness );
subplot_height_ratio = 1 / 3;
lower_subplot_height = subplot_height_ratio * total_plot_height;
mid_point_location = border_thickness + lower_subplot_height;
upper_subplot_height = 1 - ( 2 * border_thickness ) ...
    - lower_subplot_height;
subplot_width = 1 - ( 2 * border_thickness );

% upper subplot
axh_upper = axes( figh );
subplot( axh_upper );
axh_upper.Position = [ ...
    left_edge_location ...
    mid_point_location ...
    subplot_width ...
    upper_subplot_height ...
    ];
axh_upper.XScale = 'log';
axh_upper.XTickLabel = {};
axh_upper.YScale = 'log';
axh_upper.YTick = 10.^( -5 : 1 : 0 );
axh_upper.YLabel.Interpreter = 'latex';
axh_upper.YLabel.String = y_label_upper;
axh_upper.TickLabelInterpreter = 'latex';
axh_upper.Box = 'on';
hold on;

upper_plot_handle = plot( axh_upper, x_upper, y_upper );
upper_plot_handle.LineStyle = 'none';
upper_plot_handle.Marker = 'o';
upper_plot_handle.MarkerSize = 6;
upper_plot_handle.Color = 'black';

lo_limit_handle_upper = plot( ...
    axh_upper, ...
    [ x_upper( lo_limit_index ) x_upper( lo_limit_index ) ], ...
    [ 10e-6 , y_upper( lo_limit_index ) ] ...
    );
lo_limit_handle_upper.Color = 'black';
lo_limit_handle_upper.LineStyle = '--';

hi_limit_handle_upper = plot( ...
    axh_upper, ...
    [ x_upper( hi_limit_index ) x_upper( hi_limit_index ) ], ...
    [ 10e-6, y_upper( hi_limit_index ) ] ...
    );
hi_limit_handle_upper.Color = 'black';
hi_limit_handle_upper.LineStyle = '--';

% lower subplot
axh_lower = axes( figh );
subplot( axh_lower );
axh_lower.Position = [ ...
    left_edge_location ...
    bottom_edge_location ...
    subplot_width ...
    lower_subplot_height ...
    ];
axh_lower.XLim = axh_upper.XLim;
axh_lower.XScale = 'log';
axh_lower.XTick = 10.^( 0 : 1 : 3 );
axh_lower.XLabel.Interpreter = 'latex';
axh_lower.XLabel.String = x_label;
axh_lower.YLim = [ 1.1 2.1 ];
axh_lower.YTick = 1.2 : 0.2 : 2.0;
axh_lower.YAxisLocation = 'right';
axh_lower.YLabel.Interpreter = 'latex';
axh_lower.YLabel.String = y_label_lower;
axh_lower.TickLabelInterpreter = 'latex';
axh_lower.Box = 'on';
hold on;

lower_plot_handle = plot( axh_lower, x_lower, y_lower );
lower_plot_handle.LineStyle = 'none';
lower_plot_handle.Marker = '.';
lower_plot_handle.MarkerSize = 6;
lower_plot_handle.Color = 'black';

dimension_estimate_handle = plot( ...
    axh_lower, ...
    [ 1 10e4 ], ...
    [ estimate estimate ] ...
    );
dimension_estimate_handle.Color = 'black';
dimension_estimate_handle.LineStyle = '-';

hi_dimension_estimate_limit_handle = plot( ...
    axh_lower, ...
    [ 1 10e4 ], ...
    1.05 * [ estimate estimate ] ...
    );
hi_dimension_estimate_limit_handle.Color = 'black';
hi_dimension_estimate_limit_handle.LineStyle = ':';

lo_dimension_estimate_limit_handle = plot( ...
    axh_lower, ...
    [ 1 10e4 ], ...
    0.95 * [ estimate estimate ] ...
    );
lo_dimension_estimate_limit_handle.Color = 'black';
lo_dimension_estimate_limit_handle.LineStyle = ':';

lo_limit_lower_handle = plot( ...
    axh_lower, ...
    [ x_upper( lo_limit_index ) x_upper( lo_limit_index ) ], ...
    [ 0 2.1 ] ...
    );
lo_limit_lower_handle.Color = 'black';
lo_limit_lower_handle.LineStyle = '--';

hi_limit_lower_handle = plot( ...
    axh_lower, ...
    [ x_upper( hi_limit_index ) x_upper( hi_limit_index ) ], ...
    [ 0 2.1 ] ...
    );
hi_limit_lower_handle.Color = 'black';
hi_limit_lower_handle.LineStyle = '--';

% legend
legend_handle = legend( ...
    axh_upper, ...
    [ ...
        upper_plot_handle ...
        lower_plot_handle ...
        lo_limit_lower_handle ...
        dimension_estimate_handle ...
        ], ...
    { ...
        y_label_upper ...
        y_label_lower ...
        'Scaling Regime' ...
        'Dimension Estimate' ...
        } ...
    );
legend_handle.Location = 'northwest';
legend_handle.Interpreter = 'latex';

end