input_file = 'D:\Projects\Dendrite\Images\Field Outline\100\example\100_2_1_bdry_ex.bmp';
[ path, name, ext ] = fileparts( input_file );
out_ext = '.png';
output_file = [ path, filesep, name, '_disp', out_ext ];
output_sw = [ path, filesep, name, '_sw', out_ext ];
output_bdry = [ path, filesep, name, '_swb', out_ext ];
crossover_radius = 59;

im = imread( input_file );

% Display
display_stroke_radius = 3;
st_display = strel( 'disk', display_stroke_radius, 0 );
im_display = double( imdilate( im, st_display ) ) * 0.5;
im_alpha = ones(size(im));
imwrite( ...
    im_display, ...
    output_file, ...
    'Alpha', ...
    im_alpha ...
    );

% Shrinkwrap (closure)
st_crossover = strel( 'disk', crossover_radius, 0 );
im_close = double( imclose( im, st_crossover ) );
im_close_display = im_close;
im_close_alpha = double( im_close_display / 4 );
imwrite( ...
    im_close_display, ...
    output_sw, ...
    'Alpha', ...
    im_close_alpha ...
    );

% Shrinkwrap boundary
im_bdry = bwmorph( im_close, 'remove' );
im_bdry_display = uint8( imdilate( im_bdry, st_display ) ) * 255;
im_bdry_alpha = im_bdry_display;
imwrite( ...
    im_bdry_display, ...
    output_bdry, ...
    'Alpha', ...
    im_bdry_alpha ...
    );

% Value
value = sum(im_bdry(:)>0)/sum(im_close(:)>0);